apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec:
  type: NodePort
  selector:
    app: segundo-pod
  ports:
    - port: 80
      #targetPort: 80 -- Implícito se for a mesma porta 80
      nodePort: 30000
  selector:
    app: primeiro-pod
